In [ ]:
import pandas as pd
df = pd.read_csv('C:/Users/l/Desktop/pythonforder001/diabetes.csv')

In [ ]:
df['Glucose'].describe()

          Glucose         BMI
count  768.000000  768.000000
mean   120.248698   31.254557
std     31.317433    7.920138
min      0.000000    0.000000
25%     99.000000   26.400000
50%    119.000000   31.700000
75%    140.000000   36.700000
max    199.000000   55.100000

In [3]:
df[df['Glucose']==0].value_counts()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI   DiabetesPedigreeFunction  Age  Outcome
10           0        47             0              14       28.1  0.196                     38   0          1
4            0        0              7              0        19.5  0.542                     25   0          1
                                     13             53       30.8  0.624                     43   0          1
1            0        85             13             0        28.1  0.243                     38   0          1
8            0        84             29             14       34.5  0.267                     37   0          1
Name: count, dtype: int64

In [4]:
df[df['BMI']==0].value_counts()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI  DiabetesPedigreeFunction  Age  Outcome
2            117      82             20             59       0.0  0.133                     24   0          1
3            119      74             11             0        0.0  0.399                     26   0          1
6            155      75             18             14       0.0  0.531                     30   0          1
8            72       78             31             190      0.0  0.841                     30   0          1
6            167      82             7              0        0.0  0.459                     58   1          1
1            116      79             0              0        0.0  0.281                     30   0          1
4            72       70             26             111      0.0  0.756                     21   0          1
5            121      77             0              87       0.0  0.422                     38   0          1
3            131      35             0              43       0.0  0.784                     36   0          1
2            123      75             19             90       0.0  1.078                     38   1          1
3            117      84             31             0        0.0  0.279                     37   0          1
Name: count, dtype: int64

In [5]:
df[df['BMI']==0].describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,11.000000,11.000000,11.000000,11.000000,11.000000,11.0,11.000000,11.000000,11.000000
mean,3.909091,119.090909,73.727273,14.818182,54.000000,0.0,0.542091,33.454545,0.181818
std,2.119177,28.633737,13.476579,11.990147,61.269895,0.0,0.287661,9.993634,0.404520
min,1.000000,72.000000,35.000000,0.000000,0.000000,0.0,0.133000,21.000000,0.000000
25%,2.500000,116.500000,74.500000,3.500000,0.000000,0.0,0.340000,28.000000,0.000000
50%,3.000000,119.000000,77.000000,18.000000,43.000000,0.0,0.459000,30.000000,0.000000
75%,5.500000,127.000000,80.500000,23.000000,88.500000,0.0,0.770000,37.500000,0.000000
max,8.000000,167.000000,84.000000,31.000000,190.000000,0.0,1.078000,58.000000,1.000000

In [6]:
df[df['Glucose']==0].describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,5.000000,5.0,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.0
mean,5.400000,0.0,43.200000,12.400000,16.200000,28.200000,0.374400,36.200000,0.0
std,3.577709,0.0,42.304846,10.714476,21.730163,5.526301,0.194305,6.685806,0.0
min,1.000000,0.0,0.000000,0.000000,0.000000,19.500000,0.196000,25.000000,0.0
25%,4.000000,0.0,0.000000,7.000000,0.000000,28.100000,0.243000,37.000000,0.0
50%,4.000000,0.0,47.000000,13.000000,14.000000,28.100000,0.267000,38.000000,0.0
75%,8.000000,0.0,84.000000,13.000000,14.000000,30.800000,0.542000,38.000000,0.0
max,10.000000,0.0,85.000000,29.000000,53.000000,34.500000,0.624000,43.000000,0.0

In [7]:
df.loc[0:2, 'Glucose']

0    140
1    116
2    101
Name: Glucose, dtype: int64

In [8]:
df.iloc[0:3,1]

0    140
1    116
2    101
Name: Glucose, dtype: int64

In [9]:
condition1 = (df['Glucose'] >= 126)
condition2 = (df['Outcome']== 0)

In [10]:

df[condition1 & condition2]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,3,140,82,0,55,28.4,1.080,26,0
5,3,162,24,0,277,22.2,0.357,40,0
10,1,133,56,45,0,36.8,0.440,33,0
34,4,126,60,7,34,37.5,0.680,25,0
35,1,131,76,27,54,30.3,0.239,30,0
...,...,...,...,...,...,...,...,...,...
740,0,146,32,26,0,30.6,0.298,33,0
743,0,156,75,28,0,44.4,0.223,36,0
751,9,148,0,0,0,37.3,0.536,21,0
758,3,140,90,27,0,39.4,0.257,24,0
759,5,128,85,0,0,26.3,0.231,43,0

In [11]:
colom = ['Glucose','BloodPressure', 'BMI']
df[colom].replace(0, pd.NA)
df.dropna()
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,3,140,82,0,55,28.4,1.080,26,0
1,0,116,98,7,0,21.7,0.365,32,0
2,10,101,77,12,0,39.6,0.637,27,0
3,3,99,84,20,0,30.7,0.376,35,0
4,0,166,62,34,0,38.7,0.486,53,1
...,...,...,...,...,...,...,...,...,...
763,5,184,76,7,165,39.4,1.187,36,1
764,10,105,44,0,0,31.4,0.581,45,1
765,7,140,58,43,329,31.7,0.913,45,1
766,1,118,68,0,0,19.0,0.421,21,0
767,6,91,63,16,0,28.5,0.254,46,0

In [12]:
BMI_mean = df['BMI'].mean()
Glucose_mean = df['Glucose'].mean()

In [13]:
df.shape

(768, 9)

In [14]:
df['Glucose'].replace(0, Glucose_mean)

0      140.0
1      116.0
2      101.0
3       99.0
4      166.0
       ...
763    184.0
764    105.0
765    140.0
766    118.0
767     91.0
Name: Glucose, Length: 768, dtype: float64

In [15]:
df['BMI'].replace(0, BMI_mean)

0      28.4
1      21.7
2      39.6
3      30.7
4      38.7
       ...
763    39.4
764    31.4
765    31.7
766    19.0
767    28.5
Name: BMI, Length: 768, dtype: float64

In [16]:
df[df['BMI']==0].index

Index([121, 142, 405, 411, 413, 416, 581, 601, 700, 707, 737], dtype='int64')

In [17]:
df['Glucose']= df['Glucose'].replace(0, pd.NA)
df['Glucose']= df['Glucose'].fillna(Glucose_mean)

In [18]:
df['Glucose'].isna().sum()

np.int64(0)

In [19]:
df['Glucose'].min()

44

In [20]:
df['BMI_level'] = pd.cut(df["BMI"],
    bins = [0,24.5,30,50],
    labels = ['thin','normal','fat'])

In [21]:
df['BMI_level']

0      normal
1        thin
2         fat
3         fat
4         fat
        ...
763       fat
764       fat
765       fat
766      thin
767    normal
Name: BMI_level, Length: 768, dtype: category
Categories (3, str): ['thin' < 'normal' < 'fat']

In [22]:
df.groupby('Outcome')['Glucose'].agg(['mean', 'median'])

               mean median
Outcome
0        110.996487  111.0
1        139.753731  140.5

In [24]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,BMI_level
0,3,140,82,0,55,28.4,1.080,26,0,normal
1,0,116,98,7,0,21.7,0.365,32,0,thin
2,10,101,77,12,0,39.6,0.637,27,0,fat
3,3,99,84,20,0,30.7,0.376,35,0,fat
4,0,166,62,34,0,38.7,0.486,53,1,fat

In [ ]:
df['SkinThickness'] =  df['SkinThickness'].replace(0, pd.NA)
df['SkinThickness'] =  df['SkinThickness'].fillna(df['SkinThickness'].median())
# Skinthickness can not be a 0 value. It must be a positive number

In [ ]:
df['Insulin'] =  df['Insulin'].replace(0, pd.NA)
df['Insulin'] =  df['Insulin'].fillna(df['Insulin'].median())
# Insulin is a must-need hormone in human, it can not be 0.

In [30]:
df['Age_group'] = pd.cut(df['Age'],
                         bins = [18,45,50,80],
                         labels= ['Young','Middle Age','Old']

)

In [31]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,BMI_level,Age_group
0,3,140,82,21.0,55,28.4,1.080,26,0,normal,Young
1,0,116,98,7,70.5,21.7,0.365,32,0,thin,Young
2,10,101,77,12,70.5,39.6,0.637,27,0,fat,Young
3,3,99,84,20,70.5,30.7,0.376,35,0,fat,Young
4,0,166,62,34,70.5,38.7,0.486,53,1,fat,Old

In [ ]:
df.groupby('Outcome')['Glucose'].median()
#明显看出 确诊糖尿病的人群血糖中位数比未确诊的要高30

Outcome
0    111.0
1    140.5
Name: Glucose, dtype: object

In [ ]:
df.groupby('Age_group')['Glucose'].agg(['mean','median'])
#   年龄越大，血糖的水平越高，青年和中年变化不大，老年血糖明显增大

                  mean median
Age_group
Young       120.088382  118.0
Middle Age  121.618182  122.0
Old         131.944444  132.0