In [2]:
print('hello world')

hello world

In [3]:
age = 24
hobby = 'sleep'
print(f"My age is {age}")
print(f"My hobby is {hobby}")

My age is 24
My hobby is sleep

In [4]:
animals = ['dog', 'cat', 'frog', 'rabbit']
animals_2 = {
    'dog':'leo',
    'cat': 'Tom',
    'frog': 'Dim',
    'rabbit': 'Ray'
}
for animal in animals:
    print(animal)

dog
cat
frog
rabbit

In [5]:
sugar = [12, 6, 10.8, 7]
sugar_pair = {
    'dog':12,
    'cat': 6,
    'frog': 10.8,
    'rabbit': 7
}
for key, value in sugar_pair.items():
    if value > 10:
        print(key)

dog
frog

In [6]:
def check(num):
    normal_num = 10
    if num > normal_num:
        print('too high')
    else:
        print('you are fine')


check(8)
for key, value in sugar_pair.items():
    check(value)

you are fine
too high
you are fine
too high
you are fine

In [7]:
import pandas as pd
df = pd.read_csv('C:/Users/l/Desktop/pythonforder001/diabetes.csv')
print(df)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              3      140             82              0       55  28.4
1              0      116             98              7        0  21.7
2             10      101             77             12        0  39.6
3              3       99             84             20        0  30.7
4              0      166             62             34        0  38.7
..           ...      ...            ...            ...      ...   ...
763            5      184             76              7      165  39.4
764           10      105             44              0        0  31.4
765            7      140             58             43      329  31.7
766            1      118             68              0        0  19.0
767            6       91             63             16        0  28.5

     DiabetesPedigreeFunction  Age  Outcome
0                       1.080   26        0
1                       0.365   32        0
2                       0.637   27        0
3                       0.376   35        0
4                       0.486   53        1
..                        ...  ...      ...
763                     1.187   36        1
764                     0.581   45        1
765                     0.913   45        1
766                     0.421   21        0
767                     0.254   46        0

[768 rows x 9 columns]

In [8]:
df.shape

(768, 9)

In [9]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,3,140,82,0,55,28.4,1.080,26,0
1,0,116,98,7,0,21.7,0.365,32,0
2,10,101,77,12,0,39.6,0.637,27,0
3,3,99,84,20,0,30.7,0.376,35,0
4,0,166,62,34,0,38.7,0.486,53,1

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [11]:
df.dtype

AttributeError: 'DataFrame' object has no attribute 'dtype'

In [ ]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.998698,120.248698,66.597656,15.843750,49.872396,31.254557,0.485582,34.213542,0.348958
std,2.972933,31.317433,23.496197,14.959539,79.317900,7.920138,0.335057,10.039750,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,2.000000,99.000000,55.000000,0.000000,0.000000,26.400000,0.239750,26.000000,0.000000
50%,4.000000,119.000000,69.000000,13.000000,14.000000,31.700000,0.413500,33.000000,0.000000
75%,6.000000,140.000000,82.000000,26.000000,72.000000,36.700000,0.647500,41.000000,1.000000
max,16.000000,199.000000,114.000000,78.000000,600.000000,55.100000,2.400000,70.000000,1.000000

In [ ]:
df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [ ]:
df[df['Outcome'] == 1]['Glucose'].mean()

np.float64(139.7537313432836)

In [ ]:
df[df['Outcome'] == 0]['Glucose'].mean()

np.float64(109.794)

In [ ]:
df[df['Outcome'] == 0]['BMI'].mean()

np.float64(34.083582089552245)

In [13]:
df[df['Outcome'] == 1]['BMI'].mean()

np.float64(34.083582089552245)